AWSTemplateFormatVersion: '2010-09-09'
Description: VPC with Public and Private Subnets, NAT, Web Server (Apache), and EC2 Instances with SSM Access

# Template Parameters
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: AWS::EC2::KeyPair::KeyName

  VpcCIDR:
    Description: CIDR block for the VPC
    Type: String
    Default: "10.0.0.0/16"

  PublicSubnet1CIDR:
    Description: CIDR block for the Public Subnet in the first Availability Zone (AZ)
    Type: String
    Default: "10.0.1.0/24"

  PublicSubnet2CIDR:
    Description: CIDR block for the Public Subnet in the second Availability Zone (AZ)
    Type: String
    Default: "10.0.2.0/24"

  PrivateSubnet1CIDR:
    Description: CIDR block for the Private Subnet in the first Availability Zone (AZ)
    Type: String
    Default: "10.0.3.0/24"

  PrivateSubnet2CIDR:
    Description: CIDR block for the Private Subnet in the second Availability Zone (AZ)
    Type: String
    Default: "10.0.4.0/24"

  ImageId:
    Description: Amazon Linux 2 AMI ID
    Type: AWS::EC2::Image::Id
    Default: ami-02b7d5b1e55a7b5f1    

# Resources

  # VPC
  SecureVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: SvcVPC

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: SvcInternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref SecureVPC
      InternetGatewayId: !Ref InternetGateway          

  # Public Route Table and subnets
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref SecureVPC
      Tags:
        - Key: Name
          Value: PublicRouteTable
  
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref SecureVPC
      CidrBlock: !Ref PublicSubnet1CIDR
      AvailabilityZone: !Select [ 0, !GetAZs "" ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet1